_BASE_: [
  '../../../../runtime.yml',
  '../../_base_/picodet_esnet.yml',
  '../../_base_/optimizer_100e.yml',
  '../../../_base_/picodet_v2.yml'
]

# pretrain_weights: './trained_weights/output_20240503/best_model/model.pdparams'  # LCNet 2.5
pretrain_weights: './trained_weights/output_20240526/best_model/model.pdparams'  # LCNet 2.5

weights: './train_output/final_model'

find_unused_parameters: True
use_ema: true
cycle_epoch: 10
snapshot_epoch: 10

# ===================== from optimizer_100e.yml
# LearningRate:
#   base_lr: 0.1
#   schedulers:
#   - name: CosineDecay
#     max_epochs: 100
#   - name: LinearWarmup
#     start_factor: 0.1
#     steps: 300

# OptimizerBuilder:
#   optimizer:
#     momentum: 0.9
#     type: Momentum
#   regularizer:
#     factor: 0.00004
#     type: L2

epoch: 200

# ======================= reduce lerning rate by 1/4 per
LearningRate:
  base_lr: 0.25

# ====================== from picodet_lcnet_2_5x_416_coco.yml
# CSPPAN:
#   out_channels: 160

# PicoHead:
#   conv_feat:
#     name: PicoFeat
#     feat_in: 160
#     feat_out: 160
#     num_convs: 4
#     num_fpn_stride: 4
#     norm_type: bn
#     share_cls_reg: True
#   feat_in_chan: 160

# TrainReader:
#   batch_size: 48

# LearningRate:
#   base_lr: 0.3
#   schedulers:
#   - !CosineDecay
#     max_epochs: 300
#   - !LinearWarmup
#     start_factor: 0.1
#     steps: 300

# ================ from picodet_l_640_coco_lcnet.yml
# pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/PPLCNet_x2_0_pretrained.pdparams
# weights: output/picodet_l_320_coco/best_model
# find_unused_parameters: True
# use_ema: true
# epoch: 200
# snapshot_epoch: 10

# LCNet:
#   scale: 2.0
#   feature_maps: [3, 4, 5]

# LCPAN:
#   out_channels: 160

# PicoHeadV2:
#   conv_feat:
#     name: PicoFeat
#     feat_in: 160
#     feat_out: 160
#     num_convs: 4
#     num_fpn_stride: 4
#     norm_type: bn
#     share_cls_reg: True
#     use_se: True
#   feat_in_chan: 160

# LearningRate:
#   base_lr: 0.06
#   schedulers:
#   - !CosineDecay
#     max_epochs: 300
#   - !LinearWarmup
#     start_factor: 0.1
#     steps: 300

# TrainReader:
#   batch_size: 12

# originally in this file (except for scale 1.0 --> 2.5)
PicoDet:
  backbone: LCNet
  neck: CSPPAN
  head: PicoHead
  nms_cpu: True

LCNet:
  scale: 2.5
  feature_maps: [3, 4, 5]

CSPPAN:
  spatial_scales: [0.125, 0.0625, 0.03125]

metric: COCO
num_classes: 21

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: labels_fixed.json
    dataset_dir: ../dataset/_KRCASE_20240526
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: labels_fixed_val.json
    dataset_dir: ../dataset/_KRCASE_20240526

TestDataset:
  !ImageFolder
    anno_path: ../dataset/_KRCASE_20240526/labels_fixed.json

worker_num: 8
eval_height: &eval_height 800
eval_width: &eval_width 608
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomCrop: {}
  - RandomFlip: {prob: 0.5}
  - RandomDistort: {}
  batch_transforms:
  - BatchRandomResize: {target_size: [[768, 576], [800, 608], [832, 640]], random_size: True, random_interp: True, keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 6
  shuffle: true
  drop_last: true
  collate_batch: false

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 608], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false

TestReader:
  inputs_def:
    image_shape: [1, 3, 800, 608]
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 608], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
